services:
  - type: web
    name: frontend
    runtime: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
