services:
  - type: web
    name: frontend
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://food-delivery-system-eici.onrender.com
